spring:
  application:
    name: alternativerefactoringbot
  datasource:
    url: jdbc:mysql://localhost:3306/gitconfig_db?verifyServerCertificate=false&useSSL=true
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  profiles:
    active: "dev"
server:
  port: 8808
---
spring:
  profiles: dev
bot:
  botUsername: LHommeDeBot
  botPassword: Botboy55
  botToken: 6afffb5e098f5878a74dbd74e40ec71a0db304f0
  botWorkingDirectory: C:\\Users\\stefa\\Bachelorarbeit-Repos\\PullFolder\\workingRepo