spring:
  application:
    name: alternativerefactoringbot
  datasource: # gitconfig_db and DB-Address = example - replace with own
    url: jdbc:mysql://localhost:3306/gitconfig_db?verifyServerCertificate=false&useSSL=true
    username: root # example - replace with own
    password: root # example - replace with own
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  profiles:
    active: "dev"
server:
  port: 8808 # example - replace with own
---
spring:
  profiles: dev
bot:
  botRefactoringDirectory: C:/Users/exampleman/examplefolder/BotForks/ # example - replace with own